@baseUrl = http://localhost:3333

# @name sign-up
POST {{baseUrl}}/sign-up
Content-Type: application/json

{
	"name": "name",
  	"email": "john@doe.com",
  	"phoneNumber": "phoneNumber",
  	"password": "password"
}